"""Compose common and platform-specific config schemas for the local machine."""

from envy.schemas.common.config import (
    COMMON_MACHINE_FIELDS,
    COMMON_SECRET_FIELDS,
    FieldDef,
    LEGACY_CONFIG_PATHS as COMMON_LEGACY_CONFIG_PATHS,
    OBSOLETE_MACHINE_KEYS as COMMON_OBSOLETE_MACHINE_KEYS,
    OBSOLETE_SECRET_PATHS as COMMON_OBSOLETE_SECRET_PATHS,
)
from envy.utils import platform_name


if platform_name() == "darwin":
    from envy.schemas.darwin.config import (
        MACHINE_FIELDS as PLATFORM_MACHINE_FIELDS,
        SECRET_FIELDS as PLATFORM_SECRET_FIELDS,
        LEGACY_CONFIG_PATHS as PLATFORM_LEGACY_CONFIG_PATHS,
        OBSOLETE_MACHINE_KEYS as PLATFORM_OBSOLETE_MACHINE_KEYS,
        OBSOLETE_SECRET_PATHS as PLATFORM_OBSOLETE_SECRET_PATHS,
    )
else:
    from envy.schemas.linux.config import (
        MACHINE_FIELDS as PLATFORM_MACHINE_FIELDS,
        SECRET_FIELDS as PLATFORM_SECRET_FIELDS,
        LEGACY_CONFIG_PATHS as PLATFORM_LEGACY_CONFIG_PATHS,
        OBSOLETE_MACHINE_KEYS as PLATFORM_OBSOLETE_MACHINE_KEYS,
        OBSOLETE_SECRET_PATHS as PLATFORM_OBSOLETE_SECRET_PATHS,
    )


MACHINE_FIELDS = COMMON_MACHINE_FIELDS + PLATFORM_MACHINE_FIELDS
SECRET_FIELDS = COMMON_SECRET_FIELDS + PLATFORM_SECRET_FIELDS
ALL_FIELDS = MACHINE_FIELDS + SECRET_FIELDS
LEGACY_CONFIG_PATHS = COMMON_LEGACY_CONFIG_PATHS | PLATFORM_LEGACY_CONFIG_PATHS
OBSOLETE_MACHINE_KEYS = COMMON_OBSOLETE_MACHINE_KEYS + PLATFORM_OBSOLETE_MACHINE_KEYS
OBSOLETE_SECRET_PATHS = COMMON_OBSOLETE_SECRET_PATHS + PLATFORM_OBSOLETE_SECRET_PATHS


__all__ = [
    "ALL_FIELDS",
    "FieldDef",
    "LEGACY_CONFIG_PATHS",
    "MACHINE_FIELDS",
    "OBSOLETE_MACHINE_KEYS",
    "OBSOLETE_SECRET_PATHS",
    "SECRET_FIELDS",
]
