"""Darwin-only application and TCC schemas used by ``envy doctor``."""

from dataclasses import replace

from envy.schemas.common.apps import APP_SPECS as COMMON_APP_SPECS, AppSpec, PermissionReq
from envy.utils import HOME_DIR


APP_SPECS: dict[str, AppSpec] = {
    "claude-code": replace(
        COMMON_APP_SPECS["claude-code"],
        bundles=["Claude Code URL Handler.app"],
        bundle_id="com.anthropic.claude-code-url-handler",
        processes=["claude"],
    ),
    "wireshark": replace(
        COMMON_APP_SPECS["wireshark"],
        bundles=["Wireshark.app"],
        bundle_id="org.wireshark.Wireshark",
        processes=["Wireshark"],
    ),
    "vscode": replace(
        COMMON_APP_SPECS["vscode"],
        bundles=["Visual Studio Code.app"],
        bundle_id="com.microsoft.VSCode",
        processes=["Code"],
    ),
    "raycast": AppSpec(
        name="Raycast",
        casks=["raycast"],
        bundles=["Raycast.app"],
        bundle_id="com.raycast.macos",
        processes=["Raycast"],
        should_run=True,
        state_paths=[
            HOME_DIR / ".config/raycast/ai/providers.yaml",
            HOME_DIR / "Library/Application Support/com.raycast.macos/raycast-enc.sqlite",
        ],
        login_hint="Open Raycast and sign in if you use account sync, store extensions, or paid AI.",
        permissions=[
            PermissionReq("kTCCServiceAccessibility", "Accessibility", "global hotkeys and automation"),
        ],
    ),
    "codex": AppSpec(
        name="ChatGPT",
        casks=["codex", "chatgpt"],
        bundles=["ChatGPT.app"],
        bundle_id="com.openai.codex",
        commands=["codex"],
        processes=["ChatGPT", "Codex", "codex"],
        state_paths=[HOME_DIR / ".codex", HOME_DIR / "Library/Application Support/Codex"],
        checkers=["codex_auth"],
    ),
    "github-cli": AppSpec(
        name="GitHub CLI",
        brews=["gh"],
        commands=["gh"],
        checkers=["github_cli_auth"],
    ),
    "lark-cli": AppSpec(
        name="Lark CLI",
        packages=["lark-cli"],
        commands=["lark-cli"],
        checkers=["lark_cli_auth"],
    ),
    "iterm2": AppSpec(
        name="iTerm2",
        casks=["iterm2"],
        bundles=["iTerm.app", "iTerm2.app"],
        bundle_id="com.googlecode.iterm2",
        processes=["iTerm2"],
        should_run=True,
        state_paths=[HOME_DIR / "Library/Application Support/iTerm2/DynamicProfiles/Dracula.json"],
    ),
    "karabiner": AppSpec(
        name="Karabiner-Elements",
        casks=["karabiner-elements"],
        bundles=["Karabiner-Elements.app"],
        bundle_id="org.pqrs.Karabiner-Elements",
        processes=[
            "Karabiner-Elements",
            "Karabiner-Core-Service",
            "Karabiner-Menu",
            "Karabiner-VirtualHIDDevice-Daemon",
            "karabiner_console_user_server",
            "karabiner_session_monitor",
        ],
        should_run=True,
        state_paths=[HOME_DIR / ".config/karabiner/karabiner.json"],
        permissions=[
            PermissionReq(
                "kTCCServiceAccessibility",
                "Accessibility",
                "keyboard remapping",
                tcc_client="org.pqrs.Karabiner-Core-Service",
            ),
        ],
    ),
    "linearmouse": AppSpec(
        name="LinearMouse",
        casks=["linearmouse"],
        bundles=["LinearMouse.app"],
        bundle_id="com.lujjjh.LinearMouse",
        processes=["LinearMouse"],
        should_run=True,
        state_paths=[HOME_DIR / ".config/linearmouse/linearmouse.json"],
        permissions=[
            PermissionReq("kTCCServiceAccessibility", "Accessibility", "mouse behavior control"),
        ],
    ),
    "squirrel": AppSpec(
        name="Squirrel",
        casks=["squirrel-app"],
        bundles=["Squirrel.app"],
        bundle_id="im.rime.inputmethod.Squirrel",
        processes=["Squirrel"],
        should_run=True,
        state_paths=[
            HOME_DIR / "Library/Rime/squirrel.yaml",
            HOME_DIR / "Library/Preferences/im.rime.inputmethod.Squirrel.plist",
        ],
    ),
    "snipaste": AppSpec(
        name="Snipaste",
        casks=["snipaste"],
        bundles=["Snipaste.app"],
        bundle_id="com.Snipaste",
        processes=["Snipaste"],
        permissions=[
            PermissionReq("kTCCServiceScreenCapture", "Screen Recording", "screenshot capture"),
        ],
    ),
    "clash-verge": AppSpec(
        name="Clash Verge Rev",
        casks=["clash-verge-rev"],
        bundles=["Clash Verge.app", "Clash Verge Rev.app"],
        bundle_id="io.github.clash-verge-rev.clash-verge-rev",
        processes=["clash-verge", "Clash Verge"],
        state_paths=[
            HOME_DIR / "Library/Application Support/io.github.clash-verge-rev.clash-verge-rev/verge.yaml",
            HOME_DIR / "Library/Application Support/io.github.clash-verge-rev.clash-verge-rev/config.yaml",
        ],
    ),
    "cyberduck": AppSpec(
        name="Cyberduck",
        casks=["cyberduck"],
        bundles=["Cyberduck.app"],
        bundle_id="ch.sudo.cyberduck",
        processes=["Cyberduck"],
    ),
    "wps-office": AppSpec(
        name="WPS Office",
        casks=["wpsoffice-cn"],
        bundles=["wpsoffice.app", "WPS Office.app"],
        bundle_id="com.kingsoft.wpsoffice.mac",
        processes=["wpsoffice", "WPS Office"],
        login_hint="Open WPS Office and sign in if you use WPS Cloud or account sync.",
    ),
    "iina": AppSpec(
        name="IINA",
        casks=["iina"],
        bundles=["IINA.app"],
        bundle_id="com.colliderli.iina",
        commands=["iina"],
        processes=["IINA"],
    ),
    "betterdisplay": AppSpec(
        name="BetterDisplay",
        casks=["betterdisplay"],
        bundles=["BetterDisplay.app"],
        bundle_id="pro.betterdisplay.BetterDisplay",
        processes=["BetterDisplay"],
        should_run=True,
        state_paths=[HOME_DIR / "Library/Application Support/BetterDisplay"],
    ),
    "feishu": AppSpec(
        name="Feishu",
        casks=["feishu"],
        bundles=["Feishu.app", "Lark.app"],
        bundle_id="com.electron.lark",
        processes=["Feishu", "Lark"],
        state_paths=[HOME_DIR / "Library/Application Support/LarkShell/Default/Preferences"],
        login_hint="Open Feishu and confirm the account avatar/workspace is present.",
        permissions=[
            PermissionReq("kTCCServiceCamera", "Camera", "video meetings"),
            PermissionReq("kTCCServiceMicrophone", "Microphone", "video meetings"),
            PermissionReq("kTCCServiceScreenCapture", "Screen Recording", "screen sharing"),
        ],
    ),
    "tencent-meeting": AppSpec(
        name="Tencent Meeting",
        casks=["tencent-meeting"],
        bundles=["TencentMeeting.app", "腾讯会议.app"],
        bundle_id="com.tencent.meeting",
        processes=["TencentMeeting", "腾讯会议"],
        state_paths=[HOME_DIR / "Library/Application Support/com.tencent.meeting"],
        login_hint="Open Tencent Meeting and confirm the account page is signed in.",
        permissions=[
            PermissionReq("kTCCServiceCamera", "Camera", "video meetings"),
            PermissionReq("kTCCServiceMicrophone", "Microphone", "video meetings"),
            PermissionReq("kTCCServiceScreenCapture", "Screen Recording", "screen sharing"),
        ],
    ),
    "chrome": AppSpec(
        name="Google Chrome",
        casks=["google-chrome"],
        bundles=["Google Chrome.app"],
        bundle_id="com.google.Chrome",
        processes=["Google Chrome"],
        state_paths=[HOME_DIR / "Library/Application Support/Google/Chrome"],
        checkers=["chrome_account"],
    ),
    "tailscale": AppSpec(
        name="Tailscale",
        casks=["tailscale-app"],
        bundles=["Tailscale.app"],
        state_paths=[HOME_DIR / "Library/Preferences/io.tailscale.ipn.macsys.plist"],
        checkers=["tailscale_auth"],
    ),
    "orbstack": AppSpec(
        name="OrbStack",
        casks=["orbstack"],
        bundles=["OrbStack.app"],
        bundle_id="dev.orbstack.OrbStack",
        processes=["OrbStack"],
        state_paths=[HOME_DIR / ".orbstack"],
    ),
    "okular": AppSpec(
        name="Okular",
        packages=["okular"],
        bundles=["okular.app", "Okular.app"],
        bundle_id="org.kde.okular",
        processes=["okular", "Okular"],
    ),
    "zotero": AppSpec(
        name="Zotero",
        casks=["zotero"],
        bundles=["Zotero.app"],
        bundle_id="org.zotero.zotero",
        processes=["Zotero"],
        state_paths=[HOME_DIR / "Zotero", HOME_DIR / "Library/Application Support/Zotero"],
        login_hint="Open Zotero and sign in if you use library or file sync.",
    ),
    "wireguard": AppSpec(
        name="WireGuard",
        packages=["wireguard-macos-app"],
        bundles=["WireGuard.app"],
        bundle_id="com.wireguard.macos",
        processes=["WireGuard"],
    ),
    "sing-box": AppSpec(
        name="sing-box",
        packages=["sing-box"],
        commands=["sing-box"],
    ),
}

APP_ALIASES: dict[str, str] = {
    "chatgpt": "codex",
    "chatgpt-app": "codex",
    "codex-app": "codex",
    "codex-desktop": "codex",
    "openai-codex": "codex",
    "gh": "github-cli",
    "github": "github-cli",
    "feishu-cli": "lark-cli",
    "larkcli": "lark-cli",
    "larksuite-cli": "lark-cli",
    "karabiner-elements": "karabiner",
    "linear-mouse": "linearmouse",
    "squirrel-app": "squirrel",
    "rime": "squirrel",
    "clash": "clash-verge",
    "clash-verge-rev": "clash-verge",
    "google-chrome": "chrome",
    "tailscale-app": "tailscale",
    "tencentmeeting": "tencent-meeting",
    "meeting": "tencent-meeting",
    "lark": "feishu",
    "wps": "wps-office",
    "wpsoffice": "wps-office",
    "wpsoffice-cn": "wps-office",
    "zetero": "zotero",
}


__all__ = ["APP_ALIASES", "APP_SPECS"]
